# Generated by Django 3.2.7 on 2021-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.CharField(default='', max_length=512),
        ),
    ]
