# Generated by Django 3.2.7 on 2021-10-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_alter_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
