# Generated by Django 3.2.7 on 2021-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0007_auto_20211007_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
