# Generated by Django 3.2.7 on 2021-10-07 22:14

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_auto_20211007_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=Gallery.models.filepath),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=Gallery.models.filepath),
        ),
    ]
