# Generated by Django 3.2.7 on 2021-10-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0009_auto_20211008_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follwers',
            old_name='following',
            new_name='follwing',
        ),
    ]
